AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to deploy a WordPress instance on AWS Lightsail."

Parameters:
  CustomerEmail:
    Type: String
    Description: "Customer's email address, later used for URL and automatically creates an admin account within WordPress."

  CustomerPass:
    Type: String
    Description: "Customer's password, later used for automatically assign the admin account's password within WordPress."
    
  InstanceName:
    Type: String
    Description: "Unique name for the WordPress instance."

  BlueprintId:
    Type: String
    Default: "wordpress"
    Description: "Lightsail Blueprint ID for WordPress."
  
  BundleId:
    Type: String
    Default: nano_3_2
    AllowedValues:
      - nano_3_2
      - micro_3_2
      - small_3_2
      - medium_3_2
      - large_3_2
      - xlarge_3_2
      - 2xlarge_3_2
    Description: "Lightsail Bundle (Instance Size), currently default as nano_3_0 (smallest)."

      
Resources:
  WordPressInstance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref InstanceName
      BlueprintId: !Ref BlueprintId
      BundleId: !Ref BundleId
      AvailabilityZone: "ap-southeast-2a"  # Change based on your region
      UserData: 
        Fn::Base64:
          Fn::Join:
            - ""
            - - "#!/bin/bash\n"
              - "echo 'Starting WordPress admin user creation' > /var/log/wp-creation.log\n"
              - "echo 'Creating WordPress admin user...'\n"
              - "sudo /opt/bitnami/wp-cli/bin/wp user create admin "
              - !Ref CustomerEmail
              - " --user_pass='"
              - !Ref CustomerPass
              - "' --role=administrator >> /var/log/wp-creation.log 2>&1\n"
              - "echo 'WordPress admin user creation complete' >> /var/log/wp-creation.log\n"

  StaticIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: !Sub "${InstanceName}-ip"
      AttachedTo: !Ref WordPressInstance

Outputs:
  WordPressPublicIP:
    Description: "The public IP of the WordPress instance"
    #Value: !GetAtt StaticIp.IpAddress
    Value: !Join 
      - ""
      - - "Your website is at https://"
        - !GetAtt StaticIp.IpAddress
        - "/wp-admin"
